# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d5f9e2d0d56561d4c11c5802f7dc64c22df422e9802d04fab1d28ddceda8544d55cffc07ad2f50cb8ba1a7f6dd102de96c4b9b78bfe6a6a73a9b6fca150c212

test:
  secret_key_base: b20956b20ea563a37b68f6033a740e85d17ea6805f6c0a440e51dac9362de3b0fd0232a08654d82918b45246566e2472c1a40dff758612d9832b2c860db2785f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
